### ISSUE TITLE
Mansion Braithwaite

### ISSUE THREAD

**Issue by TheDeadlyCat** [VORPCORE/vorp_housing-lua#22]
hey just wanted you to know theres a door missing on the left back side of the house at the Mansion Braithwaite

**Comment by outsider31000** [comment]
hi, its not an issue with this script. its probably some ipl.

**Comment by TheDeadlyCat** [comment]
oh alright is there a way i can fix that? or i just ignore it and pretend i never saw that hahaha

**Comment by outsider31000** [comment]
not sure, ask in discord if anyones knows.

**Comment by JawshuaW** [comment]
This is still an issue to this day.
